name: LayerModel_lib
channels:
  - anaconda
  - conda-forge
dependencies:
  - matplotlib
  - networkx
  - numpy
  - pip
  - progressbar2
  - python
  - scikit-learn
  - scipy
  - texttable
  - pip:
    - opencv-python


