name: LayerModel_lib
channels:
  - defaults
  - anaconda
dependencies:
  - matplotlib=3.0.3
  - networkx
  - numpy
  - pip
  - progressbar2
  - python
  - scikit-learn
  - scipy
  - pip:
    - texttable
    - opencv-python


